name: Tag
on:
  workflow_dispatch:
    inputs:
      toBeTagAsLatestV5:
        description: 'The image tag which will be tag as latest-v5'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull and push image
        run: |
          docker pull funnyfly/tinymediamanager:v${{ github.event.inputs.toBeTagAsLatestV5 }}
          docker tag funnyfly/tinymediamanager:v${{ github.event.inputs.toBeTagAsLatestV5 }} ${{ secrets.DOCKERHUB_USERNAME }}/tinymediamanager:latest-v5
          docker push funnyfly/tinymediamanager:latest-v5
